// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwsX7n8i8xzjyBjOrUKitUF0JylGbgqRE',
    appId: '1:92396295432:web:cc9f1a55759eda037048bd',
    messagingSenderId: '92396295432',
    projectId: 'watcher-opsy-d6a27',
    authDomain: 'watcher-opsy-d6a27.firebaseapp.com',
    storageBucket: 'watcher-opsy-d6a27.firebasestorage.app',
    measurementId: 'G-B0RYM9MK7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbk-9fgrIVtg1RTpgZwH5_lbEwg6zjZ3I',
    appId: '1:92396295432:android:d94f75d6a59704897048bd',
    messagingSenderId: '92396295432',
    projectId: 'watcher-opsy-d6a27',
    storageBucket: 'watcher-opsy-d6a27.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwsX7n8i8xzjyBjOrUKitUF0JylGbgqRE',
    appId: '1:92396295432:web:2389fef15cda4fc77048bd',
    messagingSenderId: '92396295432',
    projectId: 'watcher-opsy-d6a27',
    authDomain: 'watcher-opsy-d6a27.firebaseapp.com',
    storageBucket: 'watcher-opsy-d6a27.firebasestorage.app',
    measurementId: 'G-JZYHZ922T4',
  );

}